### ISSUE TITLE
NPE while reading props of POJO with orientdb 

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-orientdb#16]
I'm having a null pointer exception when trying to access property of a POJO :+1: 
here the code who's producing this exception :  
```java
        List<Table> tables = _tableManager.getAllTables(); //this call findAll
        boolean founded = tables.parallelStream().allMatch(t -> t.getUuid().equals(uuid));
```

and here the exception :  

```java
java.lang.NullPointerException: null
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getDocFieldValue(OObjectProxyMethodHandler.java:362) ~[na:na]
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:300) ~[na:na]
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:288) ~[na:na]
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageGetMethod(OObjectProxyMethodHandler.java:277) ~[na:na]
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:103) ~[na:na]
	at model.TouchTable_$$_jvst954_0.getUuid(_$$_jvst954_0.java) ~[na:na]
	at table.TableController.lambda$wakeUpTable$1(TableController.java:60) ~[na:na]
	at table.TableController$$Lambda$6/607389686.test(Unknown Source) ~[na:na]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[na:1.8.0_25]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_25]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_25]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[na:1.8.0_25]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[na:1.8.0_25]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[na:1.8.0_25]
	at java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:306) ~[na:1.8.0_25]
	at java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:277) ~[na:1.8.0_25]
	at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115) ~[na:1.8.0_25]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_25]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_25]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) ~[na:1.8.0_25]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) ~[na:1.8.0_25]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) ~[na:1.8.0_25]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_25]
```

**Comment by cescoffier** [comment]
Why did you close it ?

**Comment by hboumedane** [comment]
sorry , i solve it !! the error was  inside the lambda expression ...
