### ISSUE TITLE
orientdbmanger exception : .NoSuchMethodError: com.orientechnologies.orient.core.Orient.isActive()Z

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-orientdb#21]
Hi, 
since this morning i'm having trouble with wisdom-orientdb plugin : 

```java
[1;31m[ERROR]	 o.o.u.l.i.o.LoggerService[0;39m [36m{[iPOJO] pool-1-thread-1}[0;39m - [ERROR]  : [wisdom:orientdb:manager] The callback method start has thrown an exception : com.orientechnologies.orient.core.Orient.isActive()Z 
java.lang.NoSuchMethodError: com.orientechnologies.orient.core.Orient.isActive()Z
	at org.wisdom.orientdb.runtime.OrientDbManagerComp.__M_start(OrientDbManagerComp.java:52) ~[na:na]
	at org.wisdom.orientdb.runtime.OrientDbManagerComp.start(OrientDbManagerComp.java) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.apache.felix.ipojo.util.Callback.call(Callback.java:233) ~[org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.util.Callback.call(Callback.java:193) ~[org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.handlers.lifecycle.callback.LifecycleCallback.call(LifecycleCallback.java:86) ~[org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.handlers.lifecycle.callback.LifecycleCallbackHandler.__M_stateChanged(LifecycleCallbackHandler.java:162) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.handlers.lifecycle.callback.LifecycleCallbackHandler.stateChanged(LifecycleCallbackHandler.java) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.InstanceManager.setState(InstanceManager.java:560) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.InstanceManager.start(InstanceManager.java:440) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.ComponentFactory.createInstance(ComponentFactory.java:179) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.IPojoFactory.createComponentInstance(IPojoFactory.java:319) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.IPojoFactory.createComponentInstance(IPojoFactory.java:240) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.extender.internal.linker.ManagedType$InstanceSupport$1.call(ManagedType.java:312) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.extender.internal.linker.ManagedType$InstanceSupport$1.call(ManagedType.java:306) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.extender.internal.queue.JobInfoCallable.call(JobInfoCallable.java:114) [org.apache.felix.ipojo-1.12.1.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

any idea ?

**Comment by cescoffier** [comment]
Jonathan is refactoring the project (see his commits from yesterday). You
should use the latest release.

2015-02-19 14:24 GMT+01:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
ok will do that thanks for the help !!

**Comment by barjo** [comment]
Hi, that's weird :open_mouth: 
Maybe due to a version conflict ? do you depend on the orient bundles and if so to the version 2.0.2.

I have re-factor the code since yesterday, so it may be hard to reproduce now.

**Comment by hboumedane** [comment]
yes i depend to orient bundles version 2.0-rc1

**Comment by hboumedane** [comment]
ok it's working now, i updated my orient bundles version to 2.0.2 and it's working now , thanks for your help.

**Comment by barjo** [comment]
:+1:
