### ISSUE TITLE
Active database is closed unexpectedly 

### ISSUE THREAD

**Issue by barjo** [wisdom-framework/wisdom-orientdb#29]
It seems that conflict appear when the application and wisdom-orientdb services are started.  

```
[ERROR]	 o.o.u.l.i.o.LoggerService {[iPOJO] pool-1-thread-1} - [ERROR]  : [todolist.controller.TodoController-0] The callback method start has thrown an exception : Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@56f4e0b0) is not active on current thread (Thread[[iPOJO] pool-1-thread-1,5,iPOJO Extender]). Current active database is: com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled@19be312d 
java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@56f4e0b0) is not active on current thread (Thread[[iPOJO] pool-1-thread-1,5,iPOJO Extender]). Current active database is: com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled@19be312d
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3097) ~[na:na]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.declareIntent(ODatabaseDocumentTx.java:1093) ~[na:na]
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.declareIntent(ODatabaseWrapperAbstract.java:270) ~[na:na]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.release(ODatabasePoolAbstract.java:223) ~[na:na]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase.release(ODatabasePoolBase.java:181) ~[na:na]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.close(OObjectDatabaseTxPooled.java:101) ~[na:na]
	at org.wisdom.orientdb.runtime.OrientDbTransactionManager.releaseDb(OrientDbTransactionManager.java:51) ~[na:na]
	at org.wisdom.orientdb.runtime.OrientDbCrudService.release(OrientDbCrudService.java:51) ~[na:na]
	at org.wisdom.orientdb.runtime.OrientDbCrudService.findAll(OrientDbCrudService.java:166) ~[na:na]
	at org.wisdom.orientdb.object.OrientDbCrud$$Proxy.findAll(Unknown Source) ~[na:na]
	at todolist.controller.TodoController.__M_start(TodoController.java:39) ~[na:na]
	at todolist.controller.TodoController.start(TodoController.java) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0]
	at org.apache.felix.ipojo.util.Callback.call(Callback.java:233) ~[org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.util.Callback.call(Callback.java:193) ~[org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.handlers.lifecycle.callback.LifecycleCallback.call(LifecycleCallback.java:86) ~[org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.handlers.lifecycle.callback.LifecycleCallbackHandler.__M_stateChanged(LifecycleCallbackHandler.java:162) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.handlers.lifecycle.callback.LifecycleCallbackHandler.stateChanged(LifecycleCallbackHandler.java) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.InstanceManager.setState(InstanceManager.java:560) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.InstanceManager.start(InstanceManager.java:440) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.ComponentFactory.createInstance(ComponentFactory.java:179) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.IPojoFactory.createComponentInstance(IPojoFactory.java:319) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.IPojoFactory.createComponentInstance(IPojoFactory.java:240) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.extender.internal.linker.ManagedType$InstanceSupport$1.call(ManagedType.java:312) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.extender.internal.linker.ManagedType$InstanceSupport$1.call(ManagedType.java:306) [org.apache.felix.ipojo-1.12.1.jar:na]
	at org.apache.felix.ipojo.extender.internal.queue.JobInfoCallable.call(JobInfoCallable.java:114) [org.apache.felix.ipojo-1.12.1.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
```

**Comment by barjo** [comment]
It happens, when an application running on an existed database start.
